### ISSUE TITLE
MELPA

### ISSUE THREAD

**Issue by dantecatalfamo** [progfolio/wordel#3]
Will this package be available through MELPA some time soon? I don't use `straight.el` to manage my package and I'd like to be able to pull this in through `use-package` 🙂

**Comment by progfolio** [comment]
I have submitted a PR to include it in MELPA:

https://github.com/melpa/melpa/pull/7871

It still needs to be reviewed/accepted.

**Comment by progfolio** [comment]
In the meantime, you could manually `git clone` the repository and point use-package's `:load-path` keyword to the repository.
e.g.

```bash
git clone https://www.github.com/progfolio/wordel.git
```

```emacs-lisp
(use-package wordel
  :ensure nil
  :load-path "/home/users/me/path/to/wordel/")
```

**Comment by progfolio** [comment]
Wordel has been added to MELPA.

**Comment by io12** [comment]
It might be a good idea to mention that it's in MELPA in the README, or to update the `straight.el` install instructions to use MELPA.

**Comment by progfolio** [comment]
Mentioned in the README. Thanks.
