### ISSUE TITLE
Feature Request: keyboard view to show already-used letters

### ISSUE THREAD

**Issue by aclarknexient** [progfolio/wordel#6]
This feature would display a standard QWERTY keyboard under the 6 guess rows. When a letter is marked "not used" it would be greyed out in the keyboard view, with relevant behaviour for green and yellow letter markers respectively.

This would bring the game more in-line with the original.

**Comment by progfolio** [comment]
I thought about adding that initially, but I like the game more without it.

**Comment by aclarknexient** [comment]
Fair enough, it's your game/port/code and I'm just super grateful that you wrote it :) Thank you!

**Comment by io12** [comment]
It could be added as an optional feature. If it's easier, it doesn't necessarily have to be in a QWERTY keyboard layout. I think just the letters A-Z in a horizontal strip would be enough for most players.

**Comment by progfolio** [comment]
> It could be added as an optional feature. If it's easier, it doesn't necessarily have to be in a QWERTY keyboard layout. I think just the letters A-Z in a horizontal strip would be enough for most players.

pull requests welcome.

**Comment by progfolio** [comment]
I've added the option `wordel-show-letter-info`. On by default.
