### ISSUE TITLE
Colour coding not working

### ISSUE THREAD

**Issue by xircon** [progfolio/wordel#8]
![image](https://user-images.githubusercontent.com/1316691/153710666-f469d422-ee33-40d2-95fe-19c4b63fdada.png)

**Comment by progfolio** [comment]
Please include all the requested information when reporting a bug.

What version of Emacs are you using? Is this bug reproducible when launching Emacs via `emacs -Q`?

**Comment by progfolio** [comment]
Closing due to lack of response. If you include the above information we can reopen and continue to troubleshoot.
