### ISSUE TITLE
wordel-mode should locally bind view-read-only to nil

### ISSUE THREAD

**Issue by 9viz** [progfolio/wordel#9]
## Describe the problem
If view-read-only is t, then it makes wordel unplayable.  But locally binding it to nil around the (read-only-mode) call makes wordel  playable; otherwise, I have to type C-x C-q.

## Directions to reproduce
M-: (setq view-read-only t) RET

M-x wordel-mode

Some keys like 's' starts isearch instead.

### Version information

* Emacs version: 29.0.50
* Operating system: NixOS

**Comment by progfolio** [comment]
This can be disabled during wordel's mode hooks.

```emacs-lisp
(defun +disable-view-mode () (view-mode -1))
(add-hook 'wordel-mode-hook #'+disable-view-mode)
```

**Comment by progfolio** [comment]
Fixed on latest main. Thanks.

**Comment by 9viz** [comment]
26 Feb 2022, 00:32 by ***@***.***:

>
>
>
>
> This can be disabled during wordel's mode hooks.
>
> (> defun>  +disable-view-mode () (> view-mode>  > -1> ))(> add-hook>  > 'wordel-mode-hook>  > #> '+disable-view-mode> )
>

Yes, i could have done that but certain Emacs mode explicitly bind view-read-only to nil which is why I mainly created an issue.  Anyway, I see that you addressed this, thanks!
